name: scanbrew
description: Servis za upravljanje artikala i cijena u ugostiteljskim objektima

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts:
  lottie:
  firebase_core:
  firebase_auth:
  fluttertoast: ^8.2.2
  cloud_firestore:
  youtube_player_flutter:
  url_launcher:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: 



flutter:
  uses-material-design: true
  assets:
   - assets/pozadina.jpeg
   - assets/lokal.png
   - assets/artikal.png
   - assets/animacija.json
